"""empty message

Revision ID: 32cd1aa56e70
Revises: 
Create Date: 2017-04-12 18:52:29.624000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cd1aa56e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('middle_name', sa.String(length=60), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('street', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('home_phone', sa.String(length=60), nullable=True),
    sa.Column('cell_phone', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_cell_phone'), 'employee', ['cell_phone'], unique=False)
    op.create_index(op.f('ix_employee_city'), 'employee', ['city'], unique=False)
    op.create_index(op.f('ix_employee_dob'), 'employee', ['dob'], unique=False)
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_first_name'), 'employee', ['first_name'], unique=False)
    op.create_index(op.f('ix_employee_home_phone'), 'employee', ['home_phone'], unique=False)
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_middle_name'), 'employee', ['middle_name'], unique=False)
    op.create_index(op.f('ix_employee_state'), 'employee', ['state'], unique=False)
    op.create_index(op.f('ix_employee_street'), 'employee', ['street'], unique=False)
    op.create_index(op.f('ix_employee_zip'), 'employee', ['zip'], unique=False)
    op.create_table('compensation_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('gross_pay', sa.Float(), nullable=True),
    sa.Column('hourly_wage', sa.Float(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_info_end_date'), 'compensation_info', ['end_date'], unique=False)
    op.create_index(op.f('ix_compensation_info_gross_pay'), 'compensation_info', ['gross_pay'], unique=False)
    op.create_index(op.f('ix_compensation_info_hourly_wage'), 'compensation_info', ['hourly_wage'], unique=False)
    op.create_index(op.f('ix_compensation_info_hours_worked'), 'compensation_info', ['hours_worked'], unique=False)
    op.create_index(op.f('ix_compensation_info_net_pay'), 'compensation_info', ['net_pay'], unique=False)
    op.create_index(op.f('ix_compensation_info_start_date'), 'compensation_info', ['start_date'], unique=False)
    op.create_table('payroll_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=60), nullable=True),
    sa.Column('account_num', sa.String(length=60), nullable=True),
    sa.Column('routing_num', sa.String(length=60), nullable=True),
    sa.Column('amount_withheld', sa.Integer(), nullable=True),
    sa.Column('num_allowances', sa.Integer(), nullable=True),
    sa.Column('claim_exemption', sa.Boolean(), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_info_account_num'), 'payroll_info', ['account_num'], unique=False)
    op.create_index(op.f('ix_payroll_info_account_type'), 'payroll_info', ['account_type'], unique=False)
    op.create_index(op.f('ix_payroll_info_amount_withheld'), 'payroll_info', ['amount_withheld'], unique=False)
    op.create_index(op.f('ix_payroll_info_claim_exemption'), 'payroll_info', ['claim_exemption'], unique=False)
    op.create_index(op.f('ix_payroll_info_num_allowances'), 'payroll_info', ['num_allowances'], unique=False)
    op.create_index(op.f('ix_payroll_info_routing_num'), 'payroll_info', ['routing_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_info_routing_num'), table_name='payroll_info')
    op.drop_index(op.f('ix_payroll_info_num_allowances'), table_name='payroll_info')
    op.drop_index(op.f('ix_payroll_info_claim_exemption'), table_name='payroll_info')
    op.drop_index(op.f('ix_payroll_info_amount_withheld'), table_name='payroll_info')
    op.drop_index(op.f('ix_payroll_info_account_type'), table_name='payroll_info')
    op.drop_index(op.f('ix_payroll_info_account_num'), table_name='payroll_info')
    op.drop_table('payroll_info')
    op.drop_index(op.f('ix_compensation_info_start_date'), table_name='compensation_info')
    op.drop_index(op.f('ix_compensation_info_net_pay'), table_name='compensation_info')
    op.drop_index(op.f('ix_compensation_info_hours_worked'), table_name='compensation_info')
    op.drop_index(op.f('ix_compensation_info_hourly_wage'), table_name='compensation_info')
    op.drop_index(op.f('ix_compensation_info_gross_pay'), table_name='compensation_info')
    op.drop_index(op.f('ix_compensation_info_end_date'), table_name='compensation_info')
    op.drop_table('compensation_info')
    op.drop_index(op.f('ix_employee_zip'), table_name='employee')
    op.drop_index(op.f('ix_employee_street'), table_name='employee')
    op.drop_index(op.f('ix_employee_state'), table_name='employee')
    op.drop_index(op.f('ix_employee_middle_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_home_phone'), table_name='employee')
    op.drop_index(op.f('ix_employee_first_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_index(op.f('ix_employee_dob'), table_name='employee')
    op.drop_index(op.f('ix_employee_city'), table_name='employee')
    op.drop_index(op.f('ix_employee_cell_phone'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
